coinconfig = {
	"coinname": "NeuCoin",
	"unit": "NEU",
	"explorertx": "https://explorer.myneucoin.com/transaction/%s/",
	"tipmsg": "Tippy ! %s tipped %i NEU to %s! (to claim /msg neutipbot help) [%s]",
	"tipprivmsg":  "Wow ! %s has tipped you %i NEU (to claim /msg neutipbot help) [%s]",
	"tiptry": "You tried to tip %i NEU but you only have %i NEU",
	"help1": "I'm neutipbot, an IRC NeuCoin tipbot. For more info do /msg neutipbot help",
	"help2": "I'm neutipbot, I'm an IRC NeuCoin tipbot. To get help about a specific command, say \2%help <command>\2  Commands: %tip %balance %withdraw %deposit %mtip %donate %help",
	"help3":"Note that to receive or send tips you should be identified with freenode services (%s). Please consider donating with %%donate. For any support questions, including those related to lost coins, query Magicking",
	"balance_confirm": "Your balance is %i NEU (+%i NEU unconfirmed)",
	"balance": "Your balance is %i NEU",
	"donated":"Donated %i NEU, thank you very much for your donation [%s]",
	"notenoughmoney": "You tried to withdraw %i NEU (+0.01 NEU TX fee) but you only have %i NEU",
	"raining": "It's raining on %s for %d NEU each (to claim /msg neutipbot help) [%s]",
}
